# Generated by Django 6.0.6 on 2026-06-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('mail', 'Email Required')], default='mail', max_length=15),
        ),
    ]
